import type {Metadata} from "next";
import {League_Spartan, Jost, Julius_Sans_One, K2D, Lalezar} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const juliusSansOne = Julius_Sans_One({
    variable: "--font-julius-sans-one",
    subsets: ["latin"],
    weight: ["400"],
});

const leagueSpartan = League_Spartan({
    variable: "--font-league-spartan",
    subsets: ["latin"],
    weight: ["200", "400", "500", "600", "700", "800", "900",],
});

const jost = Jost({
    variable: "--font-jost",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const lalezar = Lalezar({
    variable: "--font-lalezar",
    subsets: ["latin"],
    weight: ["400"],
});

const k2d = K2D({
    variable: "--font-k2d",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body
            className={`${lalezar.variable} ${jost.variable} ${juliusSansOne.variable} ${k2d.variable} ${leagueSpartan.variable} antialiased`}
        >
        <Navbar/>
        <main>{children}</main>
        <Footer/>
        </body>
        </html>
    );
}
